version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - '7850:5432'
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data: